% This is an autogenerated sample test for file rockPaperScissors
classdef testrockPaperScissors < matlab.unittest.TestCase
    methods (Test)
        function test_rockPaperScissors(testCase)
            % Specify the input(s) of rockPaperScissors
            p2 = "scissors"
            p1 = "rock"

            % Exercise the function rockPaperScissors
            actualOutput = rockPaperScissors(p1, p2);

            % Specify the expected output(s) of rockPaperScissors
            expectedOutput = "Player 1 wins"

            testCase.verifyEqual(actualOutput, expectedOutput);
        end
        function test_rockPaperScissors2(testCase)
            % Specify the input(s) of rockPaperScissors
            p2 = "paper"
            p1 = "rock"

            % Exercise the function rockPaperScissors
            actualOutput = rockPaperScissors(p1, p2);

            % Specify the expected output(s) of rockPaperScissors
            expectedOutput = "Player 2 wins"

            testCase.verifyEqual(actualOutput, expectedOutput);
        end
    end
end